name: Publish Alpha

on:
  push:
    tags:
      - '*.*.*-alpha'

jobs:
  BuildLatest:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Compile
        working-directory: ./PolicyPlus
        run: msbuild.exe -t:build -restore -p:RestorePackagesConfig=true PolicyPlus.sln /p:platform="Any CPU" /p:configuration="Release" 
      
      - name: Rename
        run: Move-Item -Path "PolicyPlus\bin\Release\Policy Plus.exe" `
          -Destination "PolicyPlusMod.exe" 

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            PolicyPlusMod.exe


  
